### ISSUE TITLE
example folder

### ISSUE THREAD

**Issue by bbraden** [190n/oncampus#1]
can you make an example folder? -ty

**Comment by 190n** [comment]
Hi! This project is kinda dead, especially because I no longer go to a school that uses onCampus. But the basic usage would be something like this (from inside the `oncampus` folder):

```py
from datetime import date

import oncampus, cli

s = oncampus.getSession('YOUR_DOMAIN', 'YOUR_USERNAME', 'YOUR_PASSWORD')

a = oncampus.getAssignments(s, startDate=date.today(), endDate=date.today(), filterMode=oncampus.FILTER_DUE)

cli.showAssignments(a)
```

This shows assignments that are due today.
